### PR TITLE
fix: expand response by default

### LINKED ISSUE #9: 优化响应展示
现在响应默认是收缩的，默认展开更好，且无需设置折叠功能。

同时，可折叠的属性向上和向下箭头不明确，用户不明白什么时候是收缩状态，什么时候是展开状态。

### PR DESCRIPTION
**Pull request by CatTail**
Close #9

### CODE REVIEW

File: packages/ruo-ui/src/components/Operation.js [hunk 1]
```diff
@@ -86,34 +86,38 @@ export default class Operation extends React.Component {
...
-        examples = response['x-examples']
-      } else {
-        examples = utility.schemaToJson(response.schema)
-      }
-
-      if (status === 'default') {
-        if (index === 0) {
-          // 只有 default response
-          status = ''
+    const keys = Object.keys(responses).map((_, index) => String(index))
```
Comment (yuzima) [inline packages/ruo-ui/src/components/Operation.js]: 多余的 console
